This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (75 entries accepted, 0 rejected).
Sorting entries....done (570 comparisons).
Generating output file Thesis.acr....done (33 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
